### ISSUE TITLE
Investigate GitHub integration for Raptor, Nimbledroid per PR

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#1]
This may be a dupe to #3, which subsumes this issue.

### Why/User Benefit/User Problem
One of the aspects that's important to test frameworks is providing immediate feedback to devs (i.e. on GitHub) so we can reduce the feedback loop: we should investigate how well our test frameworks support GitHub integration.

### Acceptance Criteria (how do I know when I’m done?)
- Identify requirements, ideals for GitHub integration
  - What's our capacity? What are we capable of running? Note: m-c may bundle commits together to run tests to save capacity; what's the right balance?
- Figure out what each test framework supports
- Report back results for greater test framework investigation #3

**Comment by mcomella** [comment]
Colin FYI: bors will allow us to run tests on each PR.

**Comment by hawkinsw** [comment]
https://developer.github.com/v3/guides/building-a-ci-server/

**Comment by hawkinsw** [comment]
https://github.com/NimbleDroid/gradle-profiler/pull/20

**Comment by hawkinsw** [comment]
> [NimbleDroid/gradle-profiler#20](https://github.com/NimbleDroid/gradle-profiler/pull/20)

This is incorporated upstream. You can see the progress of integrating ND into gradle for Fenix at https://github.com/mozilla-mobile/fenix/pull/6283

**Comment by hawkinsw** [comment]
Investigation of integration with ND complete:

See 
1. https://github.com/hawkinsw/nimbledroidrs and
1. https://github.com/hawkinsw/ndhook

**Comment by mcomella** [comment]
We'll file smaller, actionable issues if we want to make changes to our integrations so I'm going to close this to clean up the project board.
