### ISSUE TITLE
Take video side by side of Fenix from December / January vs Now (as of April)

### ISSUE THREAD

**Issue by Malclir** [mozilla-mobile/perf-frontend-issues#103]
Video for showing improvement

**Comment by Malclir** [comment]
Link to side by side video: https://streamable.com/wthl3h 

The two videos were nightly January 15th 2020 and April 20th 2020

**Comment by Malclir** [comment]
Here are 3 videos at different speed with labeled screens:

regular speed: https://streamable.com/q2bi1s
slowed down a bit: https://streamable.com/zjh7zx
extra, extra slow down: https://streamable.com/8qbgx7
[Files with all different mp4s]()

**Comment by mcomella** [comment]
Script to take the video was uploaded in https://github.com/mozilla-mobile/perf-tools/pull/1
