### ISSUE TITLE
Create "how to performance test" splash page

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#105]
We have some documentation to share with devs looking to work on Fenix performance:
- which build variants to use: https://github.com/mozilla-mobile/fenix/#guide-to-build-variants
- how to use the profiler
- how to get help

We should create a simple page that links out to these other documentations so someone completetly new to performance knows where to start.

**Comment by Malclir** [comment]
done with https://wiki.mozilla.org/Performance/How_to_get_started_on_Fenix
