### ISSUE TITLE
Fix symbol issues for 32 bit phones in simpleperf

### ISSUE THREAD

**Issue by Malclir** [mozilla-mobile/perf-frontend-issues#111]
### Why/User Benefit/User Problem
Simpleperf seems to be the lowest over head tool we have at the moment to profile our app. It allows us to also profile non-debuggable applications. However, our current implementation only works on 64 bit cpus. 

### Impact
We would be able to use simpleperf on G5s and lower end device instead of just newer device 

### Acceptance Criteria (how do I know when I’m done?)
When simpleperf works on 32 bit cpus

**Comment by mcomella** [comment]
@jeanygong We want 32-bit simpleperf support so we can get accurate startup profiles. nalexander should have context on 1) how long this will take to do and 2) if someone on our team will be capable of doing it – i.e. is it worth doing? acreskey may be able to drive this for us. 😁

**Comment by acreskeyMoz** [comment]
The libraries with symbols are fetched via this script:
https://github.com/ncalexan/simpleperf/blob/mozilla-symbols/binary_cache_builder.py

I haven't investigated yet, but it seems possible that incorrect binaries are being fetched here.

**Comment by ncalexan** [comment]
I have no particular knowledge of what might be happening here, but my first guess is that we're somehow running afoul of Android's "aarch64 -> armv7a" fallback path.  Or maybe we're using 64-bit toolchains on 32-bit binaries in a way that's producing subtly incorrect symbols.

Do we have _anybody_ who is getting correct symbols for 32-bit simpleperf?  Are we confident that something we control completely -- the Gecko profiler -- is getting correct symbols for 32-bit (only?) builds?

**Comment by acreskeyMoz** [comment]
So far we haven't seen anyone getting correct symbols for 32-bit simpleperf.

Here's one that I just tried:
https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/project.mobile.fenix.v2.performance-test.2020.05.15.latest/artifacts/public/build/armeabi-v7a/geckoNightly/target.apk

Via the simpleperf workflow
https://share.firefox.dev/2MwtXqg

However the symbols are correct when capturing via geckoprofiler:
https://share.firefox.dev/3gTJe25

When I examine the libraries that `binary_cache_builder.py` pulls in, they do look to be the 32-bit variants:

```
file ./binary_cache/data/app/org.mozilla.fenix.performancetest-sKP8J2y4RWJKszBje-zMlQ==/lib/arm/libxul.so
./binary_cache/data/app/org.mozilla.fenix.performancetest-sKP8J2y4RWJKszBje-zMlQ==/lib/arm/libxul.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=ac95676521eab6771ba1e6cb7a8410839d61671d, with debug_info, not stripped
```

**Comment by acreskeyMoz** [comment]
I wonder if we can verify if the `BuildID[sha1]=ac95676521eab6771ba1e6cb7a8410839d61671d` that I see from the fetched library (`libxulso`) is aligned with the downloaded apk?

**Comment by mcomella** [comment]
@pslawless Can you check with the Firefox Profiler team on when they'll support startup profiling for `debuggable=false` builds (if they're planning to at all)?

Triage: we won't need this functionality from simpleperf if it'll come in the Firefox Profiler.

**Comment by mcomella** [comment]
Stand-up: this isn't necessary anymore so closing. iirc, we expect the Firefox Profiler to support this use case fairly soon.
