### ISSUE TITLE
Add telemetry for user clicking on URL bar

### ISSUE THREAD

**Issue by Malclir** [mozilla-mobile/perf-frontend-issues#112]
### Why/User Benefit/User Problem
Right now, user clicking on the URL bar seems to be slow at first but increases in speed over time. However, if left alone for long enough, the execution slows down again. This probe would allow us to have more insight on what user experience instead of dealing with the 80ms - 200 ms possible time of execution and try to estimate where to focus our efforts

### Impact
We should have more insight on what our users see in term of performance

### Acceptance Criteria (how do I know when I’m done?)
We can gather performance from when the user clicks on the url bar until we see the search results displayed

**Comment by mcomella** [comment]
@MarcLeclair Do you think this is still necessary, given ecsmyth thinks it's necessary to improve performance for the first click experience?

**Comment by mcomella** [comment]
We were wondering if there is existing data for this but there's plenty for us and DS to do that's more important so we'll close. If this becomes important again, we'll very likely open a new issue and that's okay with us.
