### ISSUE TITLE
Update HANOOB, AL naming

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#119]
Action item from meeting: HANOOB/AL are unintuitive and not very extensible (e.g. how do we had cold/warm/hot to this? HHANOOB?) – let's come up with new names.

**Comment by mcomella** [comment]
We care about the following qualities for naming:
- Stability (time consuming to update, confusing to users, changing may invalidate data)
- Intuitiveness (less important than stability though)
- Consistent with existing terminology

Trying to 80-20 this, I think our options are:
1. Current naming (HANOOB) or more verbose versions (homescreen no onboarding)
1. Destination-based (homescreen, browser)
1. Intent (MAIN, VIEW)
1. User action/intent (launcher, open URL)

I feel 1 & 2 fail on stability: we may change how the screens in the app work (e.g. moving the tabs to a tabs tray instead of the homescreen, potentially making us start the app on the last used tab rather than the homescreen) which may invalidate the dashboards and naming conventions.

I feel 3-4 are both less intuitive but more stable which I think is better. If we change the behavior of the app, the dashboards may no longer be measuring what we want to measure but they'll continue to measure the same user interaction with an appropriate name. I prefer 3 because it's unambiguous and, given we're unlikely to have too many Intents, it doesn't seem all that unintuitive. 

**The scheme I propose is** `<intent-name> [cold/warm/hot] [additional modifiers]`. Modifiers may include:
- is custom tab
- opens onboarding
- is first run
- intent extras (and any changes to the app that might make)

If modifiers are excluded, we're assuming the default case, i.e. if a user sends a MAIN intent (i.e. clicks the icon in the launcher), they're more likely to not be on first run or need to see onboarding.

**Comment by mcomella** [comment]
@MarcLeclair Can you review my proposal above?

**Comment by Malclir** [comment]
@mcomella  so if I understand correctly HANOOB with the proposed case would be 
`MAIN launcher cold no-onboarding`. Did I get this right? If so, I think it's fine.  I don't think it's that unintuitive. We could also change the MAIN launcher for our landing place? I.e: `Homescreen landing cold no-onboarding` if we feel that using intent might be a bit more confusing to users with less android knowledge?

**Comment by mcomella** [comment]
CC @bdekoz for awareness

**Comment by mcomella** [comment]
> @mcomella so if I understand correctly HANOOB with the proposed case would be
> `MAIN launcher cold no-onboarding`.

@MarcLeclair I think it'd either be `MAIN` or `MAIN cold`. Currently we don't use cold/warm/hot so I'm fine omitting it. Since "no onboarding" is the default case, i.e. what users expect when they trigger a MAIN intent most of the time, I think it's okay to omit. If we want onboarding, it'd be, `MAIN cold onboarding`

**Comment by Malclir** [comment]
Then I think that's fine with me. I was just wondering if its clear for non android users the use of intent? If it's a non issue then I think this naming convention would improve our naming.

**Comment by mcomella** [comment]
> Then I think that's fine with me. I was just wondering if its clear for non android users the use of intent?

Probably not but it's only two terms to learn so I'm comfortable with that, given the other benefits that come from these values.

**Comment by mcomella** [comment]
I think this is resolved: feel free to reopen if you disagree. :)
