### ISSUE TITLE
No data updates to Fenix Startup Testing Per Device dashboard since 5/30

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#122]
The last change I can see in the dashboard is 5/28 or 5/29. Looking at the raw data, the last data is from 5/30: https://github.com/bdekoz/FNPRMS-results/blob/master/samsung_galaxy_s10-fennec-nightly-hanoob-results.csv

Note: the S7 device was unresponsive before this (it has been reset) so ignore it's data.

**Comment by bdekoz** [comment]
Ok, this should be fixed now, and the old dates filled in. I'll check back tomorrow and close it to confirm.

**Comment by bdekoz** [comment]
Fixed.
