### ISSUE TITLE
No SF startup test uploads from 6/12

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#127]
All the graphs appears to flatline on 6/12. The G5 should be more stable now so I'm not as concerned. There is a VIEW regression on the G5 recently so I'd like to see if it also occurs on these devices, however.

**Comment by bdekoz** [comment]
This is fixed now, I'd forgotten to comment the date to insert as today's date, and left it as 2020.06.07.

When this happens in the future, there will be an email alert sent to perftest-alert@mozilla.com. Maybe that will make this easier to follow.
