### ISSUE TITLE
Determine how to aggregate startup tests from multiple devices

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#129]
We have startup data from 5 devices including the G5, P2, S7, S10, P4XL. Each device seems to have different performance characteristics (G5 is fairly stable, S7 has sawtooth sometimes, high-end and low-end discrepancies) so it's difficult to interpret the data.

We should figure out a strategy for how we look at the data from these devices to make sure we're using our time and data most effectively. We should consider what % of our users represented by each phone (better understand priority of each / etc).

**Comment by bdekoz** [comment]
segmenting on test hardware, looks like 

hi - p4 > s10
medium - p2
low - s7 > g5

are plausible segments.  Within the segments, I think you can do aggregates of 2-3 devices and still retain some kind of meaning. But I'm not quite sure what we can tell about performance if we aggregate over all devices

**Comment by mcomella** [comment]
Tracking on JIRA: https://jira.mozilla.com/browse/FXP-1259
