### ISSUE TITLE
FNPRMS SF is down (August 7th)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#154]

**Comment by mcomella** [comment]
It looks like the simplified build variants landed on August 6th (according to my email) – perhaps that's related?

I see we updated FNPRMS' app ID from `org.mozilla.fenix.nightly` to `org.mozilla.fenix` around July 30 (from chat logs) so that's probably unrelated.

**Comment by mcomella** [comment]
The armv8 nightly build from the 8th works correctly, no startup crashes so it doesn't seem to be due to build failures.

**Comment by mcomella** [comment]
armv7 also checks out from the 8th.

**Comment by bdekoz** [comment]
Not seeing this, it does look like the download template is not correct.
What is the correct fenix template? What's the email?

No longer working:
fenix_url_template="
https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.DATE.latest.armeabi-v7a/artifacts/public/build/armeabi-v7a/geckoNightly/target.apk
"

**Comment by mcomella** [comment]
Updates from Matrix collab with bdekoz: here's the new URL: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mobile.v2.fenix.nightly.2020.08.10.latest.armeabi-v7a/artifacts/public/build/armeabi-v7a/target.apk

The difference is `geckoNightly` is gone. That makes sense and is fall out from the build variant merging.

**Comment by mcomella** [comment]
These are okay:
- S7 MAIN
- S10 VIEW
- P2 VIEW

I'm not sure why some would work and others would not – I'm guessing the change didn't occur in time for all runs or the dashboard is slow to update.

**Comment by bdekoz** [comment]
Hey, just an update. 

Results look stable now for fenix-nightly, we are still punting on fennec-nightly until build/release bits are changed and settle down.

I've updated the influx db to fill in results from previous outages (2020-07-[22-30], 2020-08-0[6-9]), so the grafana dashboard should be accurate as of today.

P4 results look ok to me?

**Comment by mcomella** [comment]
@bdekoz The results good to me and nice work on the backfill! I notice the Pixel 2 MAIN status is still red but the data otherwise appears to be correct so I'll go ahead and close the ticket. Thanks!
