### ISSUE TITLE
[Nimbledroid] Investigate running tests on Android 7

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#16]
### Why/User Benefit/User Problem
We currently run tests on Nexus 5, Android 5 (iirc): this is not what our users are using and we'd ideally want to run on something more modern. Let's try running on Android 7.

### Impact
This is a low effort way of making our tests slightly more representative of our users' experiences. If we don't do this, our ND tests are done on a much older device (Nexus 5) with a much older OS (Android 5).

### Acceptance Criteria (how do I know when I’m done?)
- Find available android versions & devices they run on (see Will's comment - may be done already)
- ^ Share results with team
- If possible, set up tests to run on Android 7

---

Notes
* The only way to access this might be via our configuration in the HTTP API – I've only seen Android 6 in the web UI. I believe our TaskCluster configurations define how we upload to the ND servers.
* You can contact the ND team via Slack to help you figure out where we can change the code to make this happen.

**Comment by mcomella** [comment]
No-Jun mentioned this configuration might be one line in an upload script, or the web UI.

**Comment by mcomella** [comment]
Triage: block on telemetry for Android OS versions (see also public docs); by market?

Also investigate architecture plan for GeckoView.

**Comment by hawkinsw** [comment]
From Ilya: 
nexus 5: sdk 19 to 23
Google Pixel: sdk 24 and 25

**Comment by emalysz** [comment]
From Ilya:
Please add (or update) this parameter of the curl upload command: -F device_config="android7"

**Comment by hawkinsw** [comment]
`This causes curl to POST  data  using  the  Content-Type multipart/form-data according to RFC 2388.`

**Comment by hawkinsw** [comment]
I can confirm that this works. And works as expected. Sending back to @emalysz . 

To be more explicit, I was using a REST client (insomnia) to upload an APK to ND for testing. In the body of the request, I added a field in the multipart body called `device_config` and set the text value as `android7`. I changed no other upload parameters (ie, authentication mechanism, apk in the multipart body, etc all stayed the same). ND iconifies the platform on which you are running a test next to the Scenario where it has the Android Robot with a number in its belly. That number represents the platform and is how you verify that the `device_config` value took. Let me know if this is helpful or if you need additional information.

![Screenshot from 2019-12-17 03-00-16](https://user-images.githubusercontent.com/8715530/70976546-21007b00-207a-11ea-92de-ef74fdb9c8d1.png)

**Comment by emalysz** [comment]
Nimbledroid now runs on Android5 and Android7 as of https://github.com/mozilla-mobile/fenix/pull/6985
