### ISSUE TITLE
Categorize: ready-to-work & pre-req-needed items from "Which fenix areas to improve?" meeting

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#177]
In [our meeting doc](https://docs.google.com/document/d/1VutLhlvqsJ_30t0_ciasHlD0dWFpRzqU-PdkMSiHK6s/edit), we collected several items under the "What areas of the code should we look into?" bullet. We want to bucket them into a few categories:
- "Which items are ready to start working on?" (e.g. WARM start up is immediately actionable)
- "Which items require pre-work and, briefly, what is that pre-work?" (e.g. we need to know if users use the search widget or not before we invest in it)

Please try to complete this before the planning meeting on Tuesday.

**Comment by Malclir** [comment]
From what I gathered, this is what I thought was the most appropriate:

Ready to work:
- WARM startup --> looking at more in depth / engineering work on this
-  A more "realistic" view of startup --> I.e: older profiles, profiles with add-ons, etc...
-  Disk reads --> Desktop focus is reduced/eliminating disk reads. We could investigate our disk reads on startup.
- Firefox Accounts --> Investigate interaction with syncs and its responsiveness
- APK size --> investigation could be done by us.
- Regression testing --> depends on how our user feel performance is for Fenix.
- Battery useage --> We had some reports about battery useage / multiple jobs that triggered the battery. Maybe we could look into that
- Memory footprint 


Not Ready to work:
- PWA, SPA (single page app) – emerging web. --> we would need more telemetry. One comment: "a lot of web built this way. Catch: don’t really have metrics"
- Search widget --> How many people use it. We could use some telemetry for it.
- Data usage --> Maybe need more metrics. 
- Video player --> Video minutes played is correlated to time spent in browser. However, those numbers come from the desktop side, maybe we should do our own analysis on mobile.
-  MAIN Tab restoration  --> could be tested / add telemetry
- Old profiles--> could be tested / add telemetry
- Profiling startup through simpleperf --> could be tested / add telemetry
- The content-preview mode ad --> could be tested / add telemetry
