### ISSUE TITLE
Add profiler marker for geckoview startup duration

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#191]
We're seeing mixed results from our loadUrl change https://github.com/mozilla-mobile/fenix/issues/17645 that we'd expect to see a ~700ms improvement on. One theory is GV start up is taking longer than it takes us to call `loadUrl` due to the telemetry (1.3s median, 2.1s 75%).

Let's add profiler marker(s) for GV start up so we can get a clearer picture of what's going on (I assume it's one marker with the duration of start up).

**Comment by Malclir** [comment]
related bz: https://bugzilla.mozilla.org/show_bug.cgi?id=1710471.
