### ISSUE TITLE
Ask eliserichards to move `restoreLocale` to visual completeness queue

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#193]
I noticed `restoreLocale` was added to the FenixApplication start up path. I checked with eliserichards and they said it doesn't need to happen immediately and can run, e.g. 5s after start up. Let's ask them to move it.

In general, we want to encourage folks not to add things to the pre-visual completeness start up path. So, while I don't if this is specifically a performance problem, we should ask them to move it so the team better understands the desired behavior.

Try not to spend too long on this: it's intended to be quick. File a follow-up if it goes on for longer.

**Comment by Malclir** [comment]
issue has been fixed and clsoed!
