### ISSUE TITLE
Ask mugurell what they mean by start up is slower

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#194]
In https://github.com/mozilla-mobile/fenix/issues/18680#issuecomment-809408837 mugurell mentioned start up seems slower: please ask them what they mean because we haven't observed this behavior.

Try not to spend too long on this: it's intended to be quick. File a follow-up if it goes on for longer.

**Comment by Mugurell** [comment]
Hey
Sorry for not seeing this sooner.
My comment was just based on the test - trying to act on a view shown in onboarding - which was passing until not anymore and I thought I saw in logs that the layout of HomeFragment shown for onboarding is not yet shown on the screen  so I though that was a case of a startup time regression.
But looking now in the ticket i see the layout (structure and ids) of HomeFragment so I might have confused things then and there is really no startup time regression.
Sorry for this false alarm. I think this can be closed.

**Comment by mcomella** [comment]
Got it, thanks for the update!
