### ISSUE TITLE
Find cause of 200ms Moto G5 improvement between Mar 25 and Apr 7

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#196]
_Batch this work with https://github.com/mozilla-mobile/fenix/issues/19173_

On the moto G5, we noticed ~200ms drop in start time between Mar 25 and Apr 7 ([graphs](https://treeherder.mozilla.org/perfherder/graphs?highlightAlerts=1&highlightChangelogData=1&series=mozilla-central,3201797,1,15&series=mozilla-central,3194185,1,15&series=mozilla-central,3194183,1,15&series=mozilla-central,3201765,1,15&timerange=2592000)). It appears in fenix:
![image](https://user-images.githubusercontent.com/759372/114586408-7a11fc00-9c39-11eb-9e1c-8915e707d412.png)

in geckoview:
![image](https://user-images.githubusercontent.com/759372/114586431-80a07380-9c39-11eb-8d98-69d9fc54fbd8.png)

sparky requested a backfill and will report back – we might be able to find what happened in GeckoView automatically. Note: the backfill can only go back until the gecko driver change so hopefully it landed after that.

If that doesn't work, let's investigate/bisect by hand!

**Comment by Malclir** [comment]
This could be difficult to do and the time it would take isn't worth the end result. We could re-open this issue if we ever have a script / system to backfill the missing data. If we do, we could try to just run all the commits between our two commits showed in the graph above.
