### ISSUE TITLE
Create centralized list of mobile performance tests

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#2]
### Why/User Benefit/User Problem
We're currently running many different performance tests – between GV and Fenix – and it's unclear what we're running, where there may be overlap (i.e. wasted effort and resources), and what we can change to better meet our goals.

It might be valuable to come up with a centralized list so we can better coordinate in the future.

This was also an ask from @dbolter.

### Acceptance Criteria (how do I know when I’m done?)
- Created a centralized list of mobile performance tests for GV and Fenix

---

@davehunt is working on this:
- has a Q4 OKR to create a programmatic list (on Perfherder?); **this may let us answer this inexpensively and relatively soon**
- started [a list at wiki.mozilla.org](https://wiki.mozilla.org/TestEngineering/Performance/NimbleDroid)

**Comment by mcomella** [comment]
Triage: Will mentioned he'll create a general "Fenix" wiki landing page and let Dave know, if that doesn't align with what he's working on.

**Comment by davehunt** [comment]
> has a Q4 OKR to create a programmatic list (on Perfherder?); this may let us answer this inexpensively and relatively soon

There are two related efforts here. One is a test health dashboard in Perfherder, which will show a list of performance tests that we're ingesting data for. This will not include results from Nimbledroid. This should land soon (within the next week or so). The functionality of this view will be limited initially, but there are a number of directions we could take this to provide additional value. This work can be tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1571411

The other effort is landing structured test documentation in mozilla-central to be used for ensuring documentation meets a minimal standard that can be reviewed at the patch level, and allows us to format this documentation for publication at https://firefox-source-docs.mozilla.org/. The initial focus is the Raptor test harness, and therefore excludes Nimbledroid. This will ultimately replace the documentation at https://wiki.mozilla.org/TestEngineering/Performance/Raptor#Raptor_Test_List. This work can be tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1572199

It is also possible to query ActiveData for the active performance tests running against Android hardware (excluding Nimbledroid): https://activedata.allizom.org/tools/query.html#query_id=I7+uJu5x

**Comment by mcomella** [comment]
Tracking on JIRA: https://jira.mozilla.com/browse/FXP-1260
