### ISSUE TITLE
Nimbledroid nightly uploads have stopped (Oct 29th edition)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#20]
### Why/User Benefit/User Problem
Fenix Nightly Nimbledroid uploads have stopped since the 29th.

We should take this opportunity to try to:
- Preferably & if possible, make the app owned by no user and give users permissions to modify the settings
- Make the app owned by a generic Mozilla user so we can all modify the settings, such as alerting.

### Acceptance Criteria (how do I know when I’m done?)

---

Assigning self to make this happen, even if I don't do the heavy lifting.

**Comment by mcomella** [comment]
kglazko is coordinating with me on a solution: it sounds like we'll begin uploads with one of our API keys today and work on the ideal solution in the future.

**Comment by mcomella** [comment]
We created a new app with my key and will have to see if it worked for tonight's build.

**Comment by mcomella** [comment]
One downside is that the history of the uploads may be associated with a different user account. :(

**Comment by mcomella** [comment]
Kate is going to send an email with the ideal solution: waiting on that to continue.

**Comment by hawkinsw** [comment]
Let me know if/how I can help with this!

**Comment by mcomella** [comment]
The temporary fix is working: we're working towards the long term fix.

**Comment by mcomella** [comment]
Long term fix: a mailing list was recommended in https://bugzilla.mozilla.org/show_bug.cgi?id=1593854. kglazko is looking into it

**Comment by mcomella** [comment]
I filed https://github.com/mozilla-mobile/perf-frontend-issues/issues/21 for release builds so we don't forget.

**Comment by mcomella** [comment]
Nightly uploads stopped again but it looks like it might be because of a TC migration: we'll wait to see if uploads continue tomorrow before continuing our work.

**Comment by mcomella** [comment]
Uploads are working correctly: now we just need to merge the histories.

**Comment by mcomella** [comment]
History is merged: thanks for driving, kglazko!
