### ISSUE TITLE
Collaborate with glean on "application-lifetime metrics & Interaction with ping scheduling"

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#202]
The glean team is looking at null start up metrics in https://bugzilla.mozilla.org/show_bug.cgi?id=1706637 and I suspect it will require a non-trivial refactor: let's see if they could use our expertise in making it performant.

**Comment by Malclir** [comment]
Closing for now. We can reopen if we see the need to collaborate on more glean stuff.
