### ISSUE TITLE
Identify perf needs for following release

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#207]
- [x] Find out release date, nightly branch date, last train. See goals for links to notes
- [x] Find out what changed (see doc above). Is there a special branch to test on? Do we need to do extra testing on warm page load?
- [ ] Run startup and pageload tests as well as profiling as sanity check
- [ ] Follow-up on item 2: anything else to test?

**Comment by Malclir** [comment]
No specific branch to test on. All the changes should be testable through a flag (if I understood correctly).

 I compiled a list of changes here: https://docs.google.com/document/d/1DiFaNrmnfnTdCpOpF4ihfE83H7dETRAhg_36OmRCyoA/edit
