### ISSUE TITLE
Nimbledroid release uploads have stopped (Oct 29th edition)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#21]
We're working on nightly in #20: we should also do the release builds.

**Comment by mcomella** [comment]
Nightly uploads are mostly fixed so we can start on release.

**Comment by mcomella** [comment]
This should be fixed with https://github.com/mozilla-mobile/fenix/pull/6828

**Comment by JohanLorenzo** [comment]
FYI: https://phabricator.services.mozilla.com/D55125 needs to land before next release is started. 

Edit: Done.

**Comment by mcomella** [comment]
Note: we still need to merge the historical release history into the new ND app.

**Comment by mcomella** [comment]
We don't use ND anymore.
