### ISSUE TITLE
Create replacement for FNPRMS based on locally backfilling results

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#212]
FNPRMS is hard to maintain and ensure accuracy because it's entirely automated. Let's develop a system that's more flexible because it can be run locally, e.g. a perf team member runs a script once a week and it fills in the past week's nightly's results.

**Comment by Malclir** [comment]
closed with this backfill PR : https://github.com/mozilla-mobile/perf-tools/pull/11/commits
