### ISSUE TITLE
Measure baseline (Fennec 68) cold start to homescreen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#23]
### Why/User Benefit/User Problem
We want to compare the performance of Fenix against Fennec 68 as a baseline. Our first key metric is cold startup to the homescreen: let's make an equivalent startup test for Fennec.

### Impact
Without this, we cannot establish baseline performance or measure our proposed release criteria.

### Acceptance Criteria (how do I know when I’m done?)
- Fennec 68 has cold startup to app homescreen test equivalent to Fenix
- Link to dashboard is added to perf sync document
- ? If needed, file follow-up to add this information into our dashboards

**Comment by hawkinsw** [comment]
I've been asked by Vicki and @ecsmyth to get one-off numbers to compare applink startup of Fenix with Fennec ESR68. I am going to do that today (Dec 2). I know that is not exactly what this issue represents, but I wanted to track it somewhere.

**Comment by mcomella** [comment]
This bug isn't actionable. To alleviate triage confusion, closing this issue: let's open a new issue when it's more actionable.
