### ISSUE TITLE
Determine any special conditions Nimbledroid sets up during testing

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#29]
### Why/User Benefit/User Problem
There are many things that can go on on device during testing: for example, background processing of our app, of other apps, communication on the network, etc. Sometimes these types of activities are disabled and sometimes they're not: we should determine what special conditions Nimbledroid is set up in, if any, so we better understand the environment in which we are making our performance runs.

### Impact
If we don't figure this out, we may e.g. end up tracking perf bugs that are difficult to reproduce because of something happening in the background or assuming our app is performant when it's not because background processing is disabled.

### Acceptance Criteria (how do I know when I’m done?)
- Determine & report back what changes are made to the Espresso environment used by Nimbledroid

**Comment by hawkinsw** [comment]
A related issue that I have been thinking about recently: What are the "tokens" and "configurations" included in the version of Fenix that we are profiling. In other words, are we profiling a version that
1. has metrics enabled?
1. has a Glean metrics token?
1. has a Leanplum metrics token?
1. has a push configuration?
1. has a "reasonable" release name?

**Comment by mcomella** [comment]
We don't use ND anymore.
