### ISSUE TITLE
Investigate differences between force-stop and "normal" stop of an Android Task

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/perf-frontend-issues#35]
What are the differences between the two? What are the implications for testing?

**Comment by hawkinsw** [comment]
I propose closing this. The need to for this investigation was to build a reasonable methodology for testing. It appears that we came to consensus on that methodology for a deep investigation here is not necessary. 

For the record, I did discover a few things:

1. When you issue `am force-stop <package>` when <package> is in the foreground, it *seems* to kill <package> before <package>'s "closing" lifecycle methods are invoked (`onPause()`, `onStop()`, and `onDestroy()`).
1. putting the application into the background invokes `onPause()` and `onStop()`. 
1. "swiping up" on the application (thereby dismissing it) invokes the `onDestroy()` method.
1. `am kill <package>` does *not* invoke `onDestroy()`, either. 
1. obviously, `am kill <package>` will *not* stop the package if it is in the foreground (`am force-stop <package>` will, however)

**Comment by mcomella** [comment]
Sounds good to me to close – thanks for looking into this. The fact that `onPause` & friends aren't called is particularly interesting.

fwiw, I want to start collecting our unknowns about our testing methodology in a single place so I'll remember to copy this in.
