### ISSUE TITLE
Investigate meaning of 'Displayed'

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/perf-frontend-issues#36]
https://developer.android.com/topic/performance/vitals/launch-time#time-initial

**Comment by mcomella** [comment]
@hawkinsw Is this complete? If not, imo it's not a priority for us so I think we can unassign and send it back to triage. We can prioritize this as part of the FNPRMS next steps.

**Comment by mcomella** [comment]
Cleaning up project board so closing issue I think is not in progress: I documented that we needed to do this in our "next steps" guide and it will be presented in a new, more comprehensive issue.
