### ISSUE TITLE
RecyclerView not set up correctly re-uses images for wrong viewHolder

### ISSUE THREAD

**Issue by Malclir** [mozilla-mobile/perf-frontend-issues#39]
Blocked: a separate tabs tray is replacing the home screen: https://github.com/mozilla-mobile/fenix/issues/1063. We should wait on the new implementation to see if this is still an issue.

### Why/User Benefit/User Problem
When scrolling through the HomeFragment with multiple tabs, the viewHolders don't always re-use the same images

This image shows a youtube picture used for an amazon tab.

![image](https://user-images.githubusercontent.com/16614353/70938770-d862a680-2014-11ea-8891-c8050d634058.png)

### Impact
This creates a janky UI + it looks dirty when seeing another image for another website for the wrong tab.

### Acceptance Criteria (how do I know when I’m done?)
Scrolling is smooth on homeFragment of tabs and tabView holders re-use the the right images.

**Comment by mcomella** [comment]
Moving to triage: this is blocked as mentioned in comment 0.

**Comment by mcomella** [comment]
Dupe https://github.com/mozilla-mobile/fenix/issues/8325 (since it's filed in Fenix).
