### ISSUE TITLE
Get and distribute Fenix API tokens for local performance development

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#43]
### Why/User Benefit/User Problem
Some 3rd party SDKs do not have the same performance implications if they are not provided API keys: we should provide API keys to mitigate.

### Impact
Local devs will not see all the major contributors to performance without it.

### Acceptance Criteria (how do I know when I’m done?)
- Retrieve API keys for major SDKs: Leanplum, Adjust, & Sentry
  - Note: there are sometimes Debug keys but they may not have the same perf implications as Release keys so perhaps Release keys are preferred
- Check if our use will skew data (or if it's okay because it is a different build variant) and, if so, verify that's okay with the data owners
- Distribute API keys to team (see [this guide on sharing secrets](https://mana.mozilla.org/wiki/display/SECURITY/Recommended+Tools+for+Sharing+Secrets) - FYI: I don't think we can make it convenient and leave them on gdrive)
- Follow-up bugs are filed to address any unknowns

Note: @hawkinsw has already acquired some keys and may be able to distribute them.

**Comment by hawkinsw** [comment]
FYI: Tokens should *not* be considered secret. Our production keys are readily accessible by decompiling the APK that we distribute in the Play store.

**Comment by mcomella** [comment]
I distributed Leanplum dev tokens.

In my local testing,
- Sentry is wrapped in such a way that it is not init until needed (i.e. not on startup). Not sure if we need to set up tokens urgently (fyi: I'm using a firefox-tv-debug token)
- Adjust has a relatively minimal startup time but it's in `ENVIRONMENT_SANDBOX`: maybe we don't need tokens urgently? We should do more research

**Comment by mcomella** [comment]
Triage by myself: I think Adjust & Sentry are not low hanging fruit so I don't think we need to distribute these yet. Moving to "unimportant".

**Comment by mcomella** [comment]
(copy-paste) Not a priority: closing.
