### ISSUE TITLE
Move FNPRMS to use Nightly builds

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#48]
Currently we're using `forPerformanceTest` which, due to the `debuggable` flag, has unpredictable performance characteristics, as per [our Build Variant recommendations](https://github.com/mozilla-mobile/fenix/#performance-build-variants). We should move to Nightly to get more reliable results.

### Acceptance criteria
- FNPRMS uses Nightly builds for all runs moving forward
- Open question: discuss as team? What should we do with our historical `forPerformanceTest` data? Should we do a few runs with historical builds to partially restore (as well as SNAPSHOTs let us) historical data?
- Briefly validate we get the numbers we expect: e.g. are they similar to the numbers from the prelim system? If not, file a follow-up to understand if there's an issue with our testing methodology.
  - Perhaps it doesn't matter? As long as fennec & fenix are comparable in this system

**Comment by hawkinsw** [comment]
Waiting for review on the PR.
