### ISSUE TITLE
Move FNPRMS to mozilla-mobile private repo

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#49]
It's currently available elsewhere but this will give the team access.

**Comment by mcomella** [comment]
Done.

**Comment by hawkinsw** [comment]
Please adjust permissions on this repo so that team members can approve and merge PRs

**Comment by mcomella** [comment]
@hawkinsw Can you elaborate on the issue you're seeing?

I believe the engineers should have permissions to review & merge, after my changes yesterday. ecsmyth & pslawless are not part of the Mozilla org so they needed special access (but still don't have merge permission, I think).

**Comment by hawkinsw** [comment]
` You’re not authorized to merge this pull request. `

```
Total 0 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To github.com:mozilla-mobile/FNPRMS.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:mozilla-mobile/FNPRMS.git'
```

**Comment by mcomella** [comment]
@hawkinsw This should be addressed: I deleted all branch protection. Please reopen if it's still not fixed.
