### ISSUE TITLE
Parameterize FNPRMS to run different variants

### ISSUE THREAD

**Issue by hawkinsw** [mozilla-mobile/perf-frontend-issues#51]
### Why/User Benefit/User Problem

Make it possible for FNPRMS to *easily* run different Fenix variants. This is necessary so that the team has visibility into the relative performance of different variants as Fenix development progresses. 

### Acceptance Criteria (how do I know when I’m done?)

Ability to run different variants of FNPRMS by simply changing a single parameter.

**Comment by mcomella** [comment]
I'm not sure how to interpret this so I'm going to close.
