### ISSUE TITLE
Review existing FNPRMS code

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#53]
As per our best practices, we should review our FNPRMS code – and our testing methodology – since it hasn't been done yet.

While we're at it, we should validate the code is ready to be open-sourced: i.e. it doesn't contain anything sensitive. If not, we should file a follow-up issue to address.

**Comment by mcomella** [comment]
I completed my review of FNPRMS: for things that need to change, they are:
- #65
- https://github.com/mozilla-mobile/perf-frontend-issues/issues/69
- Should we start the activity with `org.mozilla.fenix.nightly/.App` instead of hard-coding specific Activities? I believe that's the default now. For example, this might break when we move to MigrationDecisionActivity
  - _edit:_ we'll need to do this with https://github.com/mozilla-mobile/perf-frontend-issues/issues/69 because the app ID changes too
- We should be able to open source it now.

As for nits that we may wish to address:
* Rename license to LICENSE
* README can be clearer about how to run and what each script does
* common.sh: do we sleep long enough between each step? only 5s right now
* common.sh: After warm-up, should we background the app before we force-stop it to avoid interrupting a current operation?
* Can we remove profile.sh and run.sh? They don't seem to be useful anymore
* common.sh: Have we ever tested `sweep_files_older_than 30`? Something to watch out for
* times.py: needs a license, description of what the script does
* times.py: duplication in complex regex at start of script
* times.py: JSON is edited by hand instead of using the `json` module

In general, there's a decent amount of repetition that I'd like to remove – the intents & adb commands are particularly concerning – but we can address this as we iterate on the implementation.

**Comment by Malclir** [comment]
@mcomella  concerning the comment: 

> common.sh: After warm-up, should we background the app before we force-stop it to avoid interrupting a current operation?

Would it really matter, since we're uninstalling the app between each run?

**Comment by mcomella** [comment]
Merged my PR with nit fixes that do not change anything significant in the code base – https://github.com/mozilla-mobile/FNPRMS/pull/9 – and opened follow-ups for the more significant issues.

**Comment by mcomella** [comment]
> Would it really matter, since we're uninstalling the app between each run?

We don't uninstall the app between each run: https://github.com/mozilla-mobile/FNPRMS/blob/123f037d8037001188536ec977251f983945538e/common.sh#L324-L335

**Comment by mcomella** [comment]
I think we'll address the nits over time as we change the code so no need to file them all. I think there's nothing else to be done for this issue: closing.
