### ISSUE TITLE
Document unknowns with our FNPRMS measurement methodologies

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#54]
One of the advantages of using our own performance measurement system is we can document the things we're not sure are correct. Let's document what we know from FNPRMS. Consider if some things are already documented in code comments or hawkinsw's WIP doc.

Here are some additional concerns we may want to document:
* Should we do additional research to determine we might be missing? E.g. Colin suggested the Jetpack Benchmark talk from Google IO provides conditions we may want to take into account
* Do we understand `Displayed` time well enough? ([official docs](https://developer.android.com/topic/performance/vitals/launch-time#time-initial))

**Comment by hawkinsw** [comment]
In case anyone is interested in following along, here is where I am collecting my notes on the definition of `Displayed:`: https://docs.google.com/document/d/1-BZF1V88HPhWmsFV9-hFulfB7RHgTPTvVsOLwZao3Z4/edit?usp=sharing

**Comment by mcomella** [comment]
@hawkinsw As I discovered today, it might be helpful to take a note that
making the RecyclerView return 0 items does not appear to affect the
`Displayed` time so `Displayed` seems to stop before the RecycleView is
drawn. However, the user has to wait for the RV to draw before they see the
app so it's probably not capturing everything. Sorry if this is unclear:
it's getting late. :d

**Comment by hawkinsw** [comment]
Thanks! Appreciate the note. See the doc above for more information about my progress on investigating `Displayed`.

**Comment by mcomella** [comment]
Dupe https://github.com/mozilla-mobile/perf-frontend-issues/issues/81
