### ISSUE TITLE
Add Pixel 2 measurements to FNPRMS

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#57]
Our release criteria specifies we should validate performance on high-end and low-end reference devices: we should add the Pixel 2, our high-end reference device.

**Comment by hawkinsw** [comment]
I've wanted to be able to have FNPRMS target different devices for a while, so this would be a good driver for that work. In fact, right now FNPRMS assumes that there is only a single device attached to the system when it is run. If there is more than one, it will fail (or potentially run on what `adb` thinks is the default device -- I haven't tried, to be honest).

**Comment by mcomella** [comment]
> it will fail (or potentially run on what adb thinks is the default device -- I haven't tried, to be honest).

iirc, it fails. You can specify a device with `adb -s <DEVICE-SERIAL-NUMBER> <command>`.

**Comment by mcomella** [comment]
Triage: Eric wants to follow up with more data before we prioritize this issue.

**Comment by hawkinsw** [comment]
On Mon, Jan 13, 2020, 9:57 PM Michael Comella <notifications@github.com>
wrote:

> it will fail (or potentially run on what adb thinks is the default device
> -- I haven't tried, to be honest).
>
> iirc, it fails. You can specify a device with adb -s
> <DEVICE-SERIAL-NUMBER> <command>.
>

Yup, that's the one! I was just saying that it's not currently handled in the code right now. 

(edited for tone!)

**Comment by mcomella** [comment]
FNPRMS is currently hard-coded to download armv7 builds so we should make sure to change that when adding support for other devices.

**Comment by mcomella** [comment]
Dupe #66.
