### ISSUE TITLE
Get fennec cold applink measurement from FNPRMS

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#59]
We're currently getting our weekly cold applink to about:blank numbers via manual runs of our "prelim" measurement system. afaik, this is because:
* We don't have a Fennec cold applink number from FNPRMS
* Our "prelim" Fennnec cold applink number is not directly comparable to our Fenix cold applink FNPRMS number. (@hawkinsw Am I correct to say these are not comparable?)

We should get a baseline measurement of Fennec cold applink from FNPRMS so we can monitor FNPRMS Fenix Nightly for cold applink performance changes.

**Comment by hawkinsw** [comment]
Using the latest code from FNPRMS that makes manual measurement easier, here are some results for the AL cases:

1. Fenix (nightly, January 10, 2020): 599ms
2. Fennec (68): 511ms

For a delta of 17.2%. 

These two numbers are comparable in so far as they both reflect Android's `Display` time. The caveat is that they may not be comparable in terms of user-perceived startup times. See, e.g., the open issues for better understanding `Display` time and the asynchronicity of Fennec's startup UI rendering.

**Comment by mcomella** [comment]
lgtm and I passed this info on to @pslawless. I'm going to close as Done and we can reopen if pslawless has issues.
