### ISSUE TITLE
Output JSON from FNPRMS

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#61]
Request from Eric to import data to his dashboard.

**Comment by hawkinsw** [comment]
He requested a particular format:

> Array of objects with date and value keys. Date can be an iso8601 date string or number representing ms since linux epoch. Value is a number (i'd prefer ms over the current sec but that isn't a hard requirement) or null if data isn't available. For example

```
[
  {"date":"2019-12-13","value":null},
  ...
  {"date":"2020-01-12","value":0.6112999999999998},
  {"date":"2020-01-13","value":0.5827777777777777}
]
```

**Comment by hawkinsw** [comment]
@ecsmyth e.g.,

https://github.com/mozilla-mobile/fenix-nightly-perftest-results/blob/master/hanoob-results.json

?

**Comment by mcomella** [comment]
afaict, addressed by https://github.com/mozilla-mobile/FNPRMS/pull/3.
