### ISSUE TITLE
Build release-like build of Fennec for comparable measurements in FNPRMS

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#63]
We need to run the Fennec build I instrumented locally with `reportFullyDrawn` (my diff is also on Slack) in FNPRMS to get our comparable measurements to Fenix on cold startup.

If we need to enter API tokens manually, note that I believe I have access to "good enough" versions of the ones that I'm aware of.

**Comment by mcomella** [comment]
I discovered the "N" jobs in this try push seem to include the Pocket keys and may also include the Leanplum & Adjust keys as well: https://treeherder.mozilla.org/#/jobs?repo=mozilla-esr68&searchStr=android%2Crelease%2Cbuild&revision=adc498831718f05359ea4715125d899458de9024

The job name appears to be `build-android-aarch64-release/opt`. Unfortunately, I don't have the scopes to add jobs in treeherder so I'm blocked on getting access or finding an alternative way to do so.

**Comment by mcomella** [comment]
Looking at logcat, I see notes from Adjust and Leanplum:

> 2020-02-06 18:16:25.641 1503-1503/? A/Adjust: PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!

> 2020-02-06 18:16:26.184 1503-1531/? I/[INFO][Leanplum]: [com.leanplum.monitoring.ExceptionHandler::setContext::33]: LeanplumExceptionHandler could not initialize Exception Reporting.This is expected if you have not included the leanplum-monitoring module

This is indicative that both Adjust and Leanplum are included because both Adjust and Leanplum are never started if the proper build flags and API keys are not provided ([Adjust1](https://searchfox.org/mozilla-esr68/rev/6b247ceac5a7a31bdfc80635cfdb31012557fb78/mobile/android/base/java/org/mozilla/gecko/adjust/AdjustHelper.java#30), [Adjust2](https://searchfox.org/mozilla-esr68/rev/6b247ceac5a7a31bdfc80635cfdb31012557fb78/mobile/android/base/AdjustConstants.java.in#25), [Leanplum1](https://searchfox.org/mozilla-esr68/rev/6b247ceac5a7a31bdfc80635cfdb31012557fb78/mobile/android/base/MmaConstants.java.in#10)).

Unfortunately, it's unclear if we're using production or even valid keys, which could affect the behavior of the SDKs, but perhaps this is "good enough": we can compare performance to production builds (using Displayed time) to see if it's the same.

**Comment by mcomella** [comment]
I'm unblocked on adding jobs but my jobs don't have secrets. I'm working to figure out why the builds I tested above have secrets and mine don't.

**Comment by mcomella** [comment]
After talking with relman, treeherder, and various other falks, I think I have the following options to get comparable measurements from fennec:
1. Build a release build in CI, providing my own secrets locally (3 options: add directly to the source, add a custom mozconfig, use `--setenv` in try syntax)
    1. I believe all 3 expose the secrets so I'd have to come up with disposable ones, which I'm not sure is possible, especially for Leanplum
1. Build locally, including local secrets &  modifying the source code to build a release build from JVM. May be unable to build a release version of Gecko and it's impossible to get Gecko to be PGO.
1. Use the production version of the application and get the numbers a different way, e.g. by screen recording and finding the time to fully complete there

1 sounds straightforward but I don't know how I'd be able to come up with the disposable secrets. I could use dummy ones but those may not provide the same performance characteristics as the real ones. 2 is the quickest but doesn't provide realistic performance. 3 has a lot of unknowns at this point so I'm hesitant to explore it.

### Some other loose threads
* I remember a process where teams can check out branches of m-c and create releases off of them – is that something I could do? Check out a branch of m-c, land my code on it, and generate a real fennec release?
* Can I hard-code something (dummy constants? changing the branches?) to trick the SDKs to having similar performance characteristics without the tokens? For example, I can give Pocket dummy data to load, which may be roughly equivalent.

---

At present, given how long I've already spent on this (2, 3 days?), I think my best option is 2 to move quickly. We can compare the Displayed times between local and prod to get a sense of the impact on performance and extrapolate that to the `reportFullyDrawn` time we're suing as our metric. If we think the performance comparison is not good enough, we can do one of the other approaches.

**Comment by mcomella** [comment]
Here are a few pushes I made I want to keep track of:
* ryanVM triggered builds but this crashes on startup ([here](https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&selectedJob=287804914&revision=ebd7c289df4fb8399bca42951018dbad653a9c7c))
* My first job, no keys ([here](https://treeherder.mozilla.org/#/jobs?repo=try&revision=b953639cd162130a686c29235d69601e19692375))
* My second job, to verify there are no keys ([here](https://treeherder.mozilla.org/#/jobs?repo=try&revision=bfad491667be11ecf5722706f2acb6131d070235))

**Comment by mcomella** [comment]
I discovered an alternative approach: performance characteristics appear to be similar when providing invalid keys to Adjust and Leanplum so I made [a push](https://treeherder.mozilla.org/#/jobs?repo=try&revision=0c64283c3b558c069a59f7eda9f5257c08853f6a) where Adjust and Leanplum are using the default invalid tokens and I wrote custom code to store Pocket content we'd normally get from the network onto the disk on first run so we can access it like a release build on second run.

This build may be missing a few things (e.g. GCM API key) but it's about as close as we're going to get, I think.

**Comment by mcomella** [comment]
I found some local notes I made for other approaches I could try to follow:

> https://wiki.mozilla.org/Sheriffing/How_To/Beta_simulations
> e.g. ./mach try release -v 74.0b1 --tasks release-sim --migration central-to-beta --no-push
However I'm not sure if that will apply to Fennec68. And I've never tried to build my own Fennec so unfortunately I can't help there.

Second commenter:
> I'd start by checking out the 68 ESR repo/branch in a new temporary user (i.e. no .mozbuild/etc). ./mach bootstrap and see how far it gets... Then set up the right mozconfig and build with --enable-release. ryanvm might be able to help some

**Comment by mcomella** [comment]
I created a release-like build I'm comfortable with and uploaded it and its caveats to the Performance drive. The remaining work here is to:
* (optionally?) Review the `reportFullyDrawn` instrumentation
* (optionally?) Review the work-around I added for Pocket support
* (follow-up) Get measurements (in FNPRMS?) for Fennec cold startup
* (follow-up) Add measurements to dashboards

**Comment by mcomella** [comment]
emalysz is going to review my code and I filed follow-ups for getting the measurements.

**Comment by mcomella** [comment]
I have to make a new build: I found a bug where the top sites and pocket domains are fetched asynchronously and that operation is affected by the quality of network connectivity. We don’t want our “visual completeness” to vary based on network quality.

**Comment by emalysz** [comment]
I reviewed the code, and I think this Fennec build is sufficient to use in FNPRMS measurement comparisons

**Comment by mcomella** [comment]
I trigged a new build on Taskcluster: now we wait. 😁

**Comment by mcomella** [comment]
I completed the final build (20-02-18), which is available in the Android FE Perf/Builds/fennec-68 dir on the perf drive. There is nothing more to be done here.
