### ISSUE TITLE
Get comparable measurements to Fenix from Fennec release-like build, cold startup to homescreen

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#64]
We got our fennec release-like build in https://github.com/mozilla-mobile/perf-frontend-issues/issues/63: we should use that build to get cold startup measurements.

### Acceptance Criteria (how do I know when I’m done?)
* Get a defacto number for Fennec cold startup to homescreen
* Ask ecsmyth to add measurements to dashboard (ask if we need a separate issue)
* Ask pslawless to add measurements to spreadsheet

**Comment by mcomella** [comment]
Marc posted his previous approach:

> 1. adb install fennec_built_by_mcomella.apk
> 2. Start Fennec --> pass onboarding --> let pocket settle for a bit --> kill fennec
>  3. Run manual.sh using manual.sh fennec_built_by_mcommela  ha ../manual/fennec/
>        Note: ha was the "use case" (since hanoob doesn't work for fennec)
>  4. Run times.py on the results from Fennec found in /opt/fnprms/manual/fennec/
> With 30 runs ( or so) Fennec start time is 1.37272

The small changes I would make to this are:
- In step 2, we both need to pass onboarding and clear the hint text at the top of the homescreen by clicking X
  - Ensure we don't load an websites as this will change the homescreen state and break the fennec `reportFullyDrawn` method which is hard-coded to what's on the homescreen
- `manual_test.sh` will call `run_test`, which will uninstall the app, clearing the onboarding state. We should ensure that the app is not uninstalled as part of the process

Otherwise it sounds right to me.

**Comment by Malclir** [comment]
Btw @mcomella , I comment out the uninstall / install process when I ran it the first time. Should've mentionned that.

**Comment by mcomella** [comment]
@MarcLeclair Now that you have the measurement, would you mind giving it to Eric so he can update the dashboard? Then you can close this bug.
