### ISSUE TITLE
Getting Px2 numbers into FNPRMS nightly

### ISSUE THREAD

**Issue by Malclir** [mozilla-mobile/perf-frontend-issues#66]
Wondering if it would be advantageous to have px2 numbers into FNPRMS. I know I can set up the cron job locally on my desktop and just push it to the repo (could be a separate branch?).

**Comment by Malclir** [comment]
@ecsmyth added you since I'm not sure if RC talk about Pixel 2 numbers

**Comment by mcomella** [comment]
@bdekoz has P2 numbers already but hasn't yet set up the mechanism to add them to our git repository.

**Comment by ecsmyth** [comment]
I've added P2 numbers @bdekoz is generating to the [dashbaord](https://sql.telemetry.mozilla.org/dashboard/performance-fenix-release-criteria)
