### ISSUE TITLE
Get Fennec cold startup, applink baseline measurements from FNPRMS on the Pixel 2

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#71]
We want to understand how fast Fennec startup is on the P2 so we can compare against Fenix: like https://github.com/mozilla-mobile/perf-frontend-issues/issues/64 but for the Pixel 2. This probably assumes we're already measuring Fenix on the Pixel 2 regularly: https://github.com/mozilla-mobile/perf-frontend-issues/issues/57

We may already have applink measurements (from hawkinsw) but I'm not sure where those would be located. We should be able to use FNPRMS Displayed time for this.

**Comment by bdekoz** [comment]
This is completed, see

https://github.com/bdekoz/FNPRMS-results

Which has results for the P2, P4xl, and Samsung S10. 

If this is considered sufficient, please close this.

**Comment by ecsmyth** [comment]
I've added the P2 numbers @bdekoz is generating to the [release criteria dashbaord](https://sql.telemetry.mozilla.org/dashboard/performance-fenix-release-criteria)
