### ISSUE TITLE
Visual completeness time has high variance (16ms)

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#88]
We think there is a high variance in time to visual completeness because:
- Nimbledroid has a high variance
- We believe been running the build from the 24th on the G5 until the 10th or so and see a large variance in timing ([data](https://github.com/mozilla-mobile/fenix-nightly-perftest-results/blob/a94cd45b11f907a59a71011d2698db395b91a729/hanoob-results.csv#L17))

In the latter entry, the variation is from 1.179s to 1.163s = 16ms. When we're making changes that target ~10ms, this variation seems too high.

We should figure out how to solve this. Some questions:
- What creates so much variation in the time to visual completeness? Do we see the same variation in time to first frame drawn? Is there any way to reduce it or is that just Android startup?
- If we can't stop the app from having so much variance, is there a way for us to get a more consistent number from CI? e.g. geomean, more runs, running until there is little variation in the result. etc.
  - pslawless previously did an analysis looking at the deviation between runs and it did not appear to be significant. This result claims otherwise. What's with the discrepancy? Perhaps that was using time to first frame drawn or was missing the variable code? Or perhaps runs from a single day or consistent but runs across days are not?

**Comment by jimporter** [comment]
I think we'd need to do more research, but locally I found that waiting 1s between runs (after killing the previous run and before starting the new run) cut the standard deviation by about half (from ~20ms to ~10ms). We could try doing this with FNPRMS too.

**Comment by mcomella** [comment]
Triage: unimportant for now: this duration is less than 1.5% of total time but it'd be ideal to address. In the short term, we can incorporate some fixes from Jim's script into FNPRMS but the future of FNPRMS is up in the air so we shouldn't spend too long.

**Comment by mcomella** [comment]
I think we've actually found that this is a fairly good amount of variance so I"m going to close this. We can reopen if we decide against that.
