### ISSUE TITLE
FNPRMS HANOOB parsing logic is hard-coded to work on devices like G5

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#91]
logcat spits out fully drawn times like, "+551ms". Sometimes, it does, "+551ms (total 1m331s)". For the same launch command, this behavior appears to change between devices: the G5 uses the latter and the P2 uses the former.

I didn't realize this so I landed https://github.com/mozilla-mobile/FNPRMS/pull/20 to switch from non-total times to total times to support the G5: instead, we should actively support both. We should take total if it's available, otherwise fall back to non-total. This code is in times.py and we should add this ability to both `fennec-nightly` and `fennec` code.

In the current implementation, our G5 metrics should work correctly but runs on other devices may not, including runs if people use FNPRMS for local testing. Applink is unaffected & should work in all configurations.

**Comment by mcomella** [comment]
Placing In Progress: this is potentially necessary for what bdekoz is working on.

**Comment by bdekoz** [comment]
Oops, posted commentary on this in FNPRMS#20, the original thread. I'll post the patch here tho.

;)

**Comment by mcomella** [comment]
Merged in https://github.com/mozilla-mobile/FNPRMS/pull/27.
