### ISSUE TITLE
Update SF FNPRMS to latest: run on fennecNightly, etc.

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#93]
Blocked on fixing parsing logic: #91.

In https://github.com/mozilla-mobile/perf-frontend-issues/issues/69, we added fennecNightly support to the G5 in TOR. However, we're filing this follow-up to get it to work in SF on devices such as the P2.

**Comment by bdekoz** [comment]
Oops, this has been fixed for some time. SF runs on both fenix and fennec, but should probably be run on

fennec-nightly

and 

fennec-beta or whatever it is that people are actually using, release-wise

See:
https://github.com/bdekoz/FNPRMS-results

Can I close this?

**Comment by mcomella** [comment]
I can confirm that these are visible! If we want to change the build variants these run on, we'll open a new bug but that's a good call out.

Thanks bdekoz! I'll close.
