### ISSUE TITLE
Recalculate FNPRMS AL baseline on Fennec 68

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/perf-frontend-issues#96]
It seems to be completely wrong, for some reason (1.5s rather than 3s).

**Comment by Malclir** [comment]
Re ran with the following build: https://archive.mozilla.org/pub/mobile/releases/68.6.0/android-api-16/

Version: 68.6.0

Time: 2.28552seconds for App Link using FNPRMS manual testing which is 25 iterations. That is without uninstalling / installing the app after every run.

**Comment by mcomella** [comment]
Reopening: @ecsmyth can you update the baseline on the dashboard? (is it possible for us to update it to save you time?)

**Comment by ecsmyth** [comment]
Updated
